// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tyuiu.oop.SidorovAY.NetCoreWebAppMVC.DataModels;

#nullable disable

namespace tyuiu.oop.SidorovAY.NetCoreWebAppMVC.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20231101051524_AddParent")]
    partial class AddParent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("tyuiu.oop.SidorovAY.NetCoreWebAppMVC.DataModels.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("tyuiu.oop.SidorovAY.NetCoreWebAppMVC.DataModels.Person", b =>
                {
                    b.HasOne("tyuiu.oop.SidorovAY.NetCoreWebAppMVC.DataModels.Person", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("tyuiu.oop.SidorovAY.NetCoreWebAppMVC.DataModels.Person", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
